### ISSUE TITLE
React Foundational Tests

### ISSUE THREAD

**Issue by knolnsokn** [beer-garden/react-ui#163]
Unit tests needed for the following:

- [ ] Request View Page
  - [ ] Request View Table
  - [ ] Request View Output 
  - [ ] ? Request View Parameters
