### ISSUE TITLE
Request creation form

### ISSUE THREAD

**Issue by west270** [beer-garden/react-ui#41]
There are still some options from beer garden `parameters` that need implemented or need tested after issue #39 is closed.

Parameter Options:
- [x] key
- [x] display_name
- [x] optional
- [x] default
- [x] description
- [x] parameters
- [x] nullable
- [x] multi (needs tested when adding custom renderers) 
- [x] choices (needs testing with different parameter types)
- [x] maximum and minimum (needs testing with different parameter types and with `multi = true`)
- [ ] regex
- [ ] form_input_type
- [x] type_info
- [x] type:
  - [x] string
  - [x] date (model needs to be reformatted to integer before submitting)
  - [x] datetime (model needs to be reformatted to integer before submitting)
  - [x] boolean
  - [x] dictionary
  - [x] integer
  - [x] float
  - [x] ~base64 (will need a custom renderer)~ *will not do*
  - [x] bytes (will need a custom renderer)
- [ ] #37
