### ISSUE TITLE
Command forms quality of life changes

### ISSUE THREAD

**Issue by west270** [beer-garden/react-ui#410]
Dynamic commands
- [ ] add info when dependent is not defined
- [ ] command/url add indication when values are loading
- [ ] handle axios response error and show error

Parameter types
- [ ] dates / bytes fix label so it does not overlap placeholder
- [ ] make integer errors consistent with rest of form when input value is not an integer

Other settings or issues
- [ ] regex show error message when pattern does not match
- [ ] add ability to clear fields
- [ ] update job form to use react hook forms and update create job path to use new command form
- [ ] rename files appropriately once the old command form is no longer needed
