### ISSUE TITLE
React Foundational

### ISSUE THREAD

**Issue by jlrpnbbngtn** [beer-garden/react-ui#51]
This issue will track all foundational/bootstrapping work to bring the react-ui app up to feature-par with the legacy angular-ui app.

- [ ] Refactor/redesign tables to be easier to use and look nice
   - [x]  Systems
   - [x] Commands
   - [x] Requests
   - [ ] Request view
   - [ ] Scheduler
   - [ ] Job (may not need a table; to be decided)
   - [ ] Garden Management
   - [ ] Garden View
- [ ] Minor improvements 
   - [ ] Add timezone options to date pickers (used, for example, in table filters)
   - [ ] Allow the menu bar to be pinned open
   - [ ] Add a logout button/link to the menu bar
- [ ] Bug fixes
   - [ ] #53
- [ ] Research
   - [ ] Look into *react-query* use for this project
- [ ] Cleanup
   - [ ] Edit *service* files to remove unused code
   - [ ] Remove the use of type *any* wherever it's used
